name: Selenium UI Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'MoGYSD.Selenium/**'
      - '.github/workflows/selenium-tests.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'MoGYSD.Selenium/**'
      - '.github/workflows/selenium-tests.yml'

env:
  DOTNET_VERSION: '9.0.x'
  CHROME_VERSION: 'latest'

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: '114.0.5735.198'
    
    - name: Verify Chrome installation
      run: |
        google-chrome --version
        chromedriver --version
        
    - name: Create appsettings.json
      run: |
        mkdir -p MoGYSD.Selenium
        cat > MoGYSD.Selenium/appsettings.json << 'EOF'
        {
          "AppSettings": {
            "BaseUrl": "${{ secrets.APP_BASE_URL }}",
            "AdminUsername": "${{ secrets.ADMIN_USERNAME }}",
            "AdminPassword": "${{ secrets.ADMIN_PASSWORD }}",
            "Headless": "true"
          }
        }
        EOF

    - name: Install dependencies
      working-directory: MoGYSD.Selenium
      run: |
        dotnet restore --no-cache
        dotnet build --no-restore --configuration Release

    - name: Install ChromeDriver
      run: |
        # Install ChromeDriver that matches the installed Chrome version
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '(\d+\.\d+\.\d+\.\d+)')
        echo "Chrome version: $CHROME_VERSION"
        CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d. -f1)
        echo "Chrome major version: $CHROME_MAJOR_VERSION"
        
        # Download and install ChromeDriver using WebDriverManager
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.10.0/selenium-server-4.10.0.jar
        java -jar selenium-server-4.10.0.jar --version
        
        # Also install the traditional way as fallback
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version
      
    - name: Run tests
      working-directory: MoGYSD.Selenium
      env:
        PATH: ${{ env.PATH }}:/usr/local/bin
        CHROMEWEBDRIVER: /usr/local/bin
      run: |
        echo "Running tests with:"
        echo "Chrome path: $(which google-chrome)"
        echo "ChromeDriver path: $(which chromedriver)"
        dotnet test --no-build --verbosity normal --configuration Release --logger "GitHubActions;displayName=Test {DisplayName} ({FullyQualifiedName})"
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: MoGYSD.Selenium/TestResults/**/*
        retention-days: 7