name: Selenium UI Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'MoGYSD.Selenium/**'
      - '.github/workflows/selenium-tests.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'MoGYSD.Selenium/**'
      - '.github/workflows/selenium-tests.yml'

env:
  DOTNET_VERSION: '9.0.x'
  CHROME_VERSION: 'latest'

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest-stable'
    
    - name: Verify Chrome installation
      run: |
        google-chrome --version
        chromedriver --version
        
    - name: Create appsettings.json
      run: |
        mkdir -p MoGYSD.Selenium
        cat > MoGYSD.Selenium/appsettings.json << 'EOF'
        {
          "AppSettings": {
            "BaseUrl": "${{ secrets.APP_BASE_URL }}",
            "AdminUsername": "${{ secrets.ADMIN_USERNAME }}",
            "AdminPassword": "${{ secrets.ADMIN_PASSWORD }}",
            "Headless": "true"
          }
        }
        EOF

    - name: Install dependencies
      working-directory: MoGYSD.Selenium
      run: |
        dotnet restore --no-cache
        dotnet build --no-restore --configuration Release

    - name: Set Chrome binary path
      run: |
        echo "CHROME_PATH=$(which google-chrome)" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV
      with:
        chrome-version: 'latest'
        
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '(\d+\.\d+\.\d+\.\d+)')
        CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d. -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json" | jq -r ".builds.\"$CHROME_MAJOR_VERSION\".version")
        wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
      
    - name: Run tests
      working-directory: MoGYSD.Selenium
      env:
        CHROME_PATH: ${{ env.CHROME_PATH }}
        CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
      run: |
        echo "Running tests with:"
        echo "Chrome path: $CHROME_PATH"
        echo "ChromeDriver path: $CHROMEDRIVER_PATH"
        dotnet test --no-build --verbosity normal --configuration Release --logger "GitHubActions;displayName=Test {DisplayName} ({FullyQualifiedName})"
      env:
        PATH: ${{ env.PATH }}:/usr/local/share/chromedriver-linux64
        CHROMEWEBDRIVER: /usr/local/share/chromedriver-linux64
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: MoGYSD.Selenium/TestResults/**/*
        retention-days: 7